### ISSUE TITLE
Update `_includes/analytics.html` so it can be configured via `config.yml`

### ISSUE THREAD

**Issue by zazazack** [zazazack/zazazack.github.io#6]
- [x] In `_includes/analytics.html` wrap the ga-tracking code as follows: 

```liquid
{% if page.analytics %}
# ga-tracking here
{% endif %}
```

- [x] Under `# Defaults` add the following to `config.yml`

```yaml
# Defaults
defaults:
    -
        scope:
            path: ""
        values:
            analytics: true
```
